name: Run CompareFilesData On GitHub Action
on:
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      
      - name: Running the CompareFilesData Test
        run: python3 CompareFilesData.py